django_blog/apps/accounts/urls.py
from django.urls import path

from .views import ProfileUpdateView, ProfileDetailView, UserRegisterView, UserLoginView, UserLogoutView, VerifyEmailView

app_name = 'accounts'

urlpatterns = [
    path("user/edit/", ProfileUpdateView.as_view(), name="profile_edit"),
    path("user/<str:slug>/", ProfileDetailView.as_view(), name="profile_detail"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("verify-email/", VerifyEmailView.as_view(), name="verify_email"),
]

django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from apps.blog.sitemaps import PostSitemap
from apps.blog.feeds import LatestPostFeed
from django.conf.urls.i18n import i18n_patterns


handler403 = "apps.blog.views.tr_handler403"
handler404 = "apps.blog.views.tr_handler404"
handler500 = "apps.blog.views.tr_handler500"


sitemaps = {
    "posts": PostSitemap,
}

"""
Непереводимые стандартные шаблоны URL-адресов и шаблоны можно 
комбинировать в рамках i18n_patterns, 
чтобы некоторые шаблоны содержали языковой префикс, а другие – нет.
"""

urlpatterns = [
    path("admin/", admin.site.urls),
    path("rosetta/", include("rosetta.urls")),
    path("api/", include("apps.django_blog_api.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("django-ckeditor-5/", include('django_ckeditor_5.urls')),
    path("feeds/latest/", LatestPostFeed(), name="latest_post_feed"),
    path('', include('django_prometheus.urls')),
]

urlpatterns += i18n_patterns(
    path("", include("apps.blog.urls")),
    path("", include("apps.accounts.urls", namespace='accounts')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls", namespace='djdt'))]

django_blog/apps/accounts/models.py
import uuid
from datetime import timedelta
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.urls import reverse
from apps.services.utils import unique_slugify
from django.utils import timezone
from django.core.cache import cache


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(verbose_name="URL", max_length=255, blank=True, unique=True)
    avatar = models.ImageField(
        verbose_name="Аватар",
        upload_to="images/avatars/%Y/%m/%d/",
        default="images/avatars/default.png",
        blank=True,
        validators=[FileExtensionValidator(allowed_extensions=("png", "jpg", "jpeg"))],
    )
    bio = models.TextField(max_length=500, blank=True, verbose_name="Информация о себе")
    birth_date = models.DateField(null=True, blank=True, verbose_name="Дата рождения")
    email_verification_code = models.CharField(max_length=6, blank=True, null=True, verbose_name="Код подтверждения email")
    email_verified = models.BooleanField(default=False, verbose_name="Email подтвержден")
    code_created_at = models.DateTimeField(null=True, blank=True, verbose_name="Время создания кода")

    def is_online(self):
        last_seen = cache.get(f"last-seen-{self.user.id}")
        if last_seen is not None and timezone.now() < last_seen + timedelta(seconds=200):
            return True
        return False

    class Meta:
        """
        Сортировка, название таблицы в базе данных
        """

        ordering = ("user",)
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"

    def save(self, *args, **kwargs):
        """
        Сохранение полей модели при их отсутствии заполнения
        """
        if not self.slug:
            self.slug = unique_slugify(self, self.user.username)
        super().save(*args, **kwargs)

    def __str__(self):
        """
        Возвращение строки
        """
        return self.user.username

    def get_absolute_url(self):
        """
        Ссылка на профиль
        """
        return reverse("accounts:profile_detail", kwargs={"slug": self.slug})

django_blog/apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.conf import settings
from django_recaptcha.fields import ReCaptchaField


from .models import Profile


class UserUpdateForm(forms.ModelForm):
    """
    Форма обновления данных пользователя
    """

    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"class": "form-control mb-1"}))
    email = forms.EmailField(widget=forms.TextInput(attrs={"class": "form-control mb-1"}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"class": "form-control mb-1"}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"class": "form-control mb-1"}))

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name")

    def clean_email(self):
        """
        Проверка email на уникальность
        """
        email = self.cleaned_data.get("email")
        username = self.cleaned_data.get("username")
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError("Email адрес должен быть уникальным")
        return email


class ProfileUpdateForm(forms.ModelForm):
    """
    Форма обновления данных профиля пользователя
    """

    slug = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"class": "form-control mb-1"}))
    birth_date = forms.DateField(widget=forms.TextInput(attrs={"class": "form-control mb-1"}))
    bio = forms.CharField(max_length=500, widget=forms.Textarea(attrs={"rows": 5, "class": "form-control mb-1"}))

    avatar = forms.ImageField(widget=forms.FileInput(attrs={"class": "form-control mb-1"}))

    class Meta:
        model = Profile
        fields = ("slug", "birth_date", "bio", "avatar")


class UserRegisterForm(UserCreationForm):
    """
    Переопределенная форма регистрации пользователей
    """

    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email", "first_name", "last_name")

    def clean_email(self):
        """
        Проверка email на уникальность
        """
        email = self.cleaned_data.get("email")
        username = self.cleaned_data.get("username")
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError("Такой email уже используется в системе")
        return email

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы регистрации
        """
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update({"placeholder": "Придумайте свой логин"})
        self.fields["email"].widget.attrs.update({"placeholder": "Введите свой email"})
        self.fields["first_name"].widget.attrs.update({"placeholder": "Ваше имя"})
        self.fields["last_name"].widget.attrs.update({"placeholder": "Ваша фамилия"})
        self.fields["password1"].widget.attrs.update({"placeholder": "Придумайте свой пароль"})
        self.fields["password2"].widget.attrs.update({"placeholder": "Повторите придуманный пароль"})
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control", "autocomplete": "off"})


class UserLoginForm(AuthenticationForm):
    """
    Форма авторизации на сайте
    """

    recaptcha = ReCaptchaField()

    class Meta:
        model = User
        fields = ["username", "password", "recaptcha"]

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы регистрации
        """
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs["placeholder"] = "Логин пользователя"
        self.fields["username"].widget.attrs["class"] = "form-control"
        self.fields["password"].widget.attrs["placeholder"] = "Пароль пользователя"
        self.fields["password"].widget.attrs["class"] = "form-control"
        self.fields["username"].label = "Логин"

django_blog/apps/accounts/views.py
from django.views.generic import DetailView, UpdateView, CreateView
from django.db import transaction
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import LoginView, LogoutView

from .models import Profile
from .forms import UserUpdateForm, ProfileUpdateForm, UserRegisterForm, UserLoginForm


class ProfileDetailView(DetailView):
    """
    Представление для просмотра профиля
    """

    model = Profile
    context_object_name = "profile"
    template_name = "accounts/profile_detail.html"
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f"Профиль пользователя: {self.object.user.username}"
        return context


class ProfileUpdateView(UpdateView):
    """
    Представление для редактирования профиля
    """

    model = Profile
    form_class = ProfileUpdateForm
    template_name = "accounts/profile_edit.html"

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f"Редактирование профиля пользователя: {self.request.user.username}"
        if self.request.POST:
            context["user_form"] = UserUpdateForm(self.request.POST, instance=self.request.user)
        else:
            context["user_form"] = UserUpdateForm(instance=self.request.user)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        user_form = context["user_form"]
        with transaction.atomic():
            if all([form.is_valid(), user_form.is_valid()]):
                user_form.save()
                form.save()
            else:
                context.update({"user_form": user_form})
                return self.render_to_response(context)
        return super(ProfileUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy("accounts:profile_detail", kwargs={"slug": self.object.slug})


class UserRegisterView(SuccessMessageMixin, CreateView):
    """
    Представление регистрации на сайте с формой регистрации
    """

    form_class = UserRegisterForm
    success_url = reverse_lazy("home")
    template_name = "accounts/user_register.html"
    success_message = "Вы успешно зарегистрировались. Можете войти на сайт!"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Регистрация на сайте"
        return context


class UserLoginView(SuccessMessageMixin, LoginView):
    """
    Авторизация на сайте
    """

    form_class = UserLoginForm
    template_name = "accounts/user_login.html"
    next_page = "home"
    success_message = "Добро пожаловать на сайт!"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Авторизация на сайте"
        return context


class UserLogoutView(LogoutView):
    """
    Выход с сайта
    """

    next_page = "home"

django_blog/templates/accounts/profile_detail.html
{% extends 'main.html' %}

{% block content %}
<div class="card border-0">
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <figure>
                        <img src="{{ profile.avatar.url }}" class="img-fluid rounded-0" alt="{{ profile }}">
                    </figure>
                </div>
                <div class="col-md-9">
                     <h5 class="card-title">
                        {{ profile }}
                    </h5>
                    <div class="card-text">
                        <ul>
                            <li>Никнейм: {{ profile.user.username }}</li>
                            {% if profile.user.get_full_name %} <li>Имя и фамилия: {{ profile.user.get_full_name }}</li> {% endif %}
                            <li>Заходил: {{ profile.user.last_login }} | {% if profile.is_online %}Онлайн{% else %}Не в сети{% endif %}</li>
                            <li>Дата рождения: {{ profile.birth_date }}</li>
                            <li>О себе: {{ profile.bio }}</li>
                        </ul>
                    {% if request.user == profile.user %} <a href="{% url 'accounts:profile_edit' %}" class="btn btn-sm btn-primary">Редактировать профиль</a> {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

django_blog/templates/accounts/profile_edit.html
{% extends 'main.html' %}

{% block content %}
<div class="card mb-3 border-0 nth-shadow">
   <div class="card-body">
      <div class="card-title nth-card-title">
         <h4>Изменение профиля</h4>
      </div>
      <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
         {{ user_form.as_p }}
         {{ form.as_p }}
         <div class="d-grid gap-2 d-md-block mt-2">
            <button type="submit" class="btn btn-dark">Подтвердить изменение профиля</button>
         </div>
      </form>
   </div>
</div>
{% endblock %}

django_blog/templates/accounts/user_login.html
{% extends 'main.html' %}

{% block content %}
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Авторизация на сайте</h4>
            </div>
            <form method="post" action="{% url 'accounts:login' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="d-grid gap-2 d-md-block mt-2">
                <button type="submit" class="btn btn-dark">Авторизоваться</button>
             </div>
            </form>
        </div>
    </div>
{% endblock %}

django_blog/templates/accounts/user_register.html
{% extends 'main.html' %}

{% block content %}
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Регистрация на сайте</h4>
            </div>
            <form method="post" action="{% url 'accounts:register' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark mt-2">Зарегистрироваться</button>
            </form>
        </div>
    </div>
{% endblock %}

django_blog/templates/accounts/verify_email.html
{% extends 'main.html' %}

{% block title %}Подтверждение Email{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="text-center">Подтверждение Email</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="verification_code">Введите код подтверждения:</label>
                            <input type="text" class="form-control" id="verification_code" name="verification_code" required>
                            <small class="form-text text-muted">Введите 6-значный код, отправленный на ваш email</small>
                        </div>
                        {% if error_message %}
                        <div class="alert alert-danger mt-3">
                            {{ error_message }}
                        </div>
                        {% endif %}
                        <button type="submit" class="btn btn-primary mt-3">Подтвердить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}