django_blog/apps/accounts/urls.py
from django.urls import path

from .views import ProfileUpdateView, ProfileDetailView, UserRegisterView, UserLoginView, UserLogoutView, VerifyEmailView

app_name = 'accounts'

urlpatterns = [
    path("user/edit/", ProfileUpdateView.as_view(), name="profile_edit"),
    path("user/<str:slug>/", ProfileDetailView.as_view(), name="profile_detail"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("verify-email/", VerifyEmailView.as_view(), name="verify_email"),
]

django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from apps.blog.sitemaps import PostSitemap
from apps.blog.feeds import LatestPostFeed
from django.conf.urls.i18n import i18n_patterns


handler403 = "apps.blog.views.tr_handler403"
handler404 = "apps.blog.views.tr_handler404"
handler500 = "apps.blog.views.tr_handler500"


sitemaps = {
    "posts": PostSitemap,
}

"""
Непереводимые стандартные шаблоны URL-адресов и шаблоны можно 
комбинировать в рамках i18n_patterns, 
чтобы некоторые шаблоны содержали языковой префикс, а другие – нет.
"""

urlpatterns = [
    path("admin/", admin.site.urls),
    path("rosetta/", include("rosetta.urls")),
    path("api/", include("apps.django_blog_api.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("django-ckeditor-5/", include('django_ckeditor_5.urls')),
    path("feeds/latest/", LatestPostFeed(), name="latest_post_feed"),
    path('', include('django_prometheus.urls')),
]

urlpatterns += i18n_patterns(
    path("", include("apps.blog.urls")),
    path("", include("apps.accounts.urls", namespace='accounts')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls", namespace='djdt'))]

django_blog/templates/footer.html
<footer class="py-5 bg-dark mt-2 mt-auto">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2025, Powered by
        Django</p></div>
</footer>

django_blog/templates/header.html
{% load i18n %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">{% trans "My Django Blog 2.0" %}</a>
        </div>
</nav>
<div class='d-flex justify-content-end '>
            {% if request.user.is_authenticated %}
        <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            {{ request.user }}
          </a>
          <ul class="dropdown-menu text-small" style="/">
            <li><a class="dropdown-item" href="{% url 'post_create' %}">Добавить статью</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:profile_detail' request.user.profile.slug %}">{% trans "My profile" %}</a></li>
            <li><hr class="dropdown-divider"></li>
            <li>
                    <form action="{% url 'accounts:logout' %}" method="post">{% csrf_token %}
                        <a href="#" class="dropdown-item" onclick="parentNode.submit();">{% trans "Log out" %}</a>
                    </form>
            </li>
          </ul>
        </div>
        {% else %}
            <ul class="nav ">
              <li><a href="{% url 'accounts:register' %}" class="nav-link px-2 link-secondary">{% trans "Registration" %}</a></li>
              <li><a href="{% url 'accounts:login' %}" class="nav-link px-2 link-dark">{% trans "Login" %}</a></li>
            </ul>
        {% endif %}
</div>

django_blog/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <title>Блог 2.0</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>

    <body class="d-flex flex-column min-vh-100">
        {% include 'header.html' %}
        <div class="container">
            <div class="row">
                <div class="col-lg-8 p-4">
                    {% include 'includes/messages.html' %}
                    {% block content %}
                    {% endblock %}
                    {% include 'pagination.html' %}
                </div>
                <div class="col-4 p-4">
                    {% include 'sidebar.html' %}
                </div>
            </div>
        </div>
        {% include 'footer.html' %}
        <script src="{% static 'backend.js' %}"></script>
        {% block script %}{% endblock %}
    </body>

</html

django_blog/templates/pagination.html
{% if is_paginated %}
    <div class="pagination p-3">
    {% for page_number in page_obj.paginator.get_elided_page_range %}
        {% if page_number == page_obj.paginator.ELLIPSIS %}
            {{page_number}}
        {% else %}
            <a href="?page={{ page_number }}" class="page-link">
                {{page_number}}
            </a>
        {% endif %}
    {% endfor %}
    </div>
{%endif%}

django_blog/templates/share.html
<div class="share-buttons mt-3">
    <h6>Поделитесь этой записью:</h6>
    <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank" class="btn btn-primary btn-sm">Facebook</a>
    <a href="https://twitter.com/intent/tweet?url={{ request.build_absolute_uri }}&text={{ post.title }}" target="_blank" class="btn btn-info btn-sm">Twitter</a>
    <a href="https://vk.com/share.php?url={{ request.build_absolute_uri }}" target="_blank" class="btn btn-secondary btn-sm">ВКонтакте</a>
    <a href="https://t.me/share/url?url={{ request.build_absolute_uri }}&text={{ post.title }}" target="_blank" class="btn btn-success btn-sm">Telegram</a>
    <a href="https://mail.google.com/mail/?view=cm&fs=1&to=&su=Интересная запись&body=Я нашел эту запись интересной: {{ request.build_absolute_uri }}" target="_blank" class="btn btn-danger btn-sm">Gmail</a>
</div>
  

django_blog/templates/sidebar.html
{% load mptt_tags %}
{% load i18n %}
   


<div class="card mb-4">
    <div class="card-header">Categories</div>
    <div class="card-body ">
        {% full_tree_for_model blog.Category as categories %}
        <ul>
            {% recursetree categories %}
                <li>
                    <a href="{{ node.get_absolute_url }}">{{ node.title }}</a>
                </li>

                {% if not node.is_leaf_node %}
                    <ul>{% endif %}
            {{ children }}
            {% if not node.is_leaf_node %}</ul>{% endif %}
            {% endrecursetree %}
        </ul>
        <div class="col">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
                {% if language.code == LANGUAGE_CODE %}
                    <u>{{ language.name_local }}</u>
                {% else %}
                    <a href="/{{ language.code }}/">{{ language.name_local }}</a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
<a href="{% url 'latest_post_feed' %}">Подписаться на RSS ленту</a>